export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const AUTH_GOOGLE_START = "AUTH_GOOGLE_START";
export const AUTH_GOOGLE_SUCCESS = "AUTH_GOOGLE_SUCCESS";
export const AUTH_GOOGLE_FAILURE = 'AUTH_GOOGLE_FAILURE';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const LOGOFF_USER = 'LOGOFF_USER';

// Events Actions
export const GET_EVENTS_START = 'GET_EVENTS_START';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const GET_EVENT_START = 'GET_EVENT_START';
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS';
export const GET_EVENT_FAILURE = 'GET_EVENT_FAILURE';

export const SAVE_EVENT_START = 'SAVE_EVENT_START';
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_FAILURE = 'SAVE_EVENT_FAILURE';

export const DELETE_EVENT_START = 'DELETE_EVENT_START';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';

export const VOTER_ACTION_START = 'VOTER_ACTION_START';
export const VOTER_ACTION_SUCCESS = 'VOTER_ACTION_SUCCESS';
export const VOTER_ACTION_FAILURE = 'VOTER_ACTION_FAILURE';

export const ADD_SESSION_FAILURE = 'ADD_SESSION_FAILURE';

export const SET_ACTION_STATE = 'SET_ACTION_STATE';
export const SET_USER_ACTION_STATE = 'SET_USER_ACTION_STATE';

export const PAYMENT_ACTION_START = 'PAYMENT_ACTION_START';
export const PAYMENT_ACTION_SUCCESS = 'PAYMENT_ACTION_SUCCESS';
export const PAYMENT_ACTION_FAILURE = 'PAYMENT_ACTION_FAILURE';